name: tikfans2
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+5
environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  # https://pub.dev/packages/dio
  dio: ^4.0.6
  # https://pub.dev/packages/steel_crypt
  steel_crypt: ^3.0.0+1
  # https://pub.dev/packages/get
  get: 4.6.4
  # https://pub.dev/packages/get_storage
  get_storage: ^2.0.3
  # https://pub.dev/packages/common_utils
  common_utils: ^2.1.0
  # https://pub.dev/packages/flutter_svg
  flutter_svg: ^1.1.6
  # https://pub.dev/packages/cached_network_image
  cached_network_image: ^3.2.3
  # https://pub.dev/packages/flutter_cache_manager
  flutter_cache_manager: ^3.3.0
  # https://pub.dev/packages/hexcolor
  hexcolor: ^3.0.1
  # https://pub.dev/packages/in_app_purchase
  in_app_purchase: ^3.1.1
  # https://pub.dev/packages/flutter_easyloading
  flutter_easyloading: ^3.0.5
  # https://pub.dev/packages/package_info_plus
  package_info_plus: ^3.0.2
  # https://pub.dev/packages/device_info_plus
  device_info_plus: ^8.0.0
  # https://pub.dev/packages/flutter_udid
  flutter_udid: ^2.0.1
  # https://pub.dev/packages/auto_size_text
  auto_size_text: ^3.0.0
  # https://pub.dev/packages/styled_text
  styled_text: ^6.0.0
  # https://pub.dev/packages/url_launcher
  url_launcher: ^6.1.7
  # https://pub.dev/packages/firebase_core
  firebase_core: ^2.4.1
  # https://pub.dev/packages/firebase_messaging
  firebase_messaging: ^14.2.1
  # https://pub.dev/packages/firebase_analytics
  firebase_analytics: ^10.1.0
  # https://pub.dev/packages/firebase_crashlytics
  firebase_crashlytics: ^3.0.9
  # https://pub.dev/packages/google_sign_in
  google_sign_in: ^5.4.2
  # https://pub.dev/packages/unity_ads_plugin
  unity_ads_plugin: ^0.3.7
  # https://pub.dev/packages/flutter_staggered_grid_view
  flutter_staggered_grid_view: ^0.6.2
  # https://pub.dev/packages/flutter_native_timezone
  flutter_native_timezone: ^2.0.0
  # https://pub.dev/packages/timezone
  # timezone: ^0.9.0
  # https://pub.dev/packages/popover
  popover: ^0.2.8
  # https://pub.dev/packages/android_play_install_referrer
  android_play_install_referrer: ^0.2.1
  # https://pub.dev/packages/flutter_keyboard_visibility
  flutter_keyboard_visibility: ^5.4.0
  # https://pub.dev/packages/easy_refresh
  easy_refresh: ^3.2.1
  # https://pub.dev/packages/flutter_fortune_wheel
  flutter_fortune_wheel: ^1.2.0
  # https://pub.dev/packages/slide_countdown  
  slide_countdown: ^0.4.0
  # https://pub.dev/packages/flutter_mailer
  flutter_mailer: ^2.0.2
  # https://pub.dev/packages/slang
  slang: ^3.7.0
  # https://pub.dev/packages/slang_flutter
  slang_flutter: ^3.7.0
  # https://pub.dev/packages/flutter_spinkit
  flutter_spinkit: ^5.1.0
  # https://pub.dev/packages/app_settings
  app_settings: ^4.2.0
  # https://pub.dev/packages/share_plus
  share_plus: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  # https://pub.dev/packages/flutter_native_splash
  flutter_native_splash: ^2.2.16
  # https://pub.dev/packages/build_runner
  build_runner: ^2.3.2
  # https://pub.dev/packages/slang_build_runner
  slang_build_runner: ^3.7.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/svg/
    - assets/json/
    - assets/svg/store/
    - assets/svg/tabbar/
    - assets/svg/universal/
    - assets/img/universal/
    - assets/svg/setting/
    - assets/img/setting/
    - assets/svg/wheel/
    - assets/img/store/
    - assets/img/login/
    - assets/img/account/
    - assets/svg/task/
    - assets/img/ad/
    - assets/img/task/
    
  fonts:
    - family: Roboto
      fonts:
          - asset: assets/fonts/Roboto-Italic.ttf
            style: italic
          - asset: assets/fonts/Roboto-Regular.ttf
            style: normal
          - asset: assets/fonts/Roboto-Medium.ttf
            weight: 600
            style: italic
          - asset: assets/fonts/Roboto-MediumItalic.ttf
            weight: 600
            style: italic